export const SET_POPFILMS="SET_POPFILMS";
export const FILM_FETCHED="FILM_FETCHED";
export const FILM_SEARCHED="FILM_SEARCHED";
export const SET_CURRENT_USER="SET_CURRENT_USER";
export const USER_FETCHED="USER_FETCHED";